version: "3.6"

services:
  hostname:
    image: rstarmer/hostname:latest
    deploy:
      mode: replicated
      replicas: 4
      placement:
        constraints: [node.role == worker]
    expose:
      - "80"

  nginx-proxy:
    image: nginx
    ports:
      - 80:8080
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    command: [nginx-debug, '-g', 'daemon off;']
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
