version: "3.3"

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: infoshare
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:latest
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == worker]

  nginx-proxy:
    image: nginx
    ports:
      - 80:8080
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    command: [nginx-debug, '-g', 'daemon off;']
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]

  wordpress:
    depends_on:
      - db
    image: wordpress:5.9.2-php7.4-apache
    volumes:
      - wordpress_data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == worker]

volumes:
  db_data:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=192.168.10.2,nfsvers=3,rw,nolock"
      device: ":/mnt/mysql"
  wordpress_data:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=192.168.10.2,nfsvers=3,rw"
      device: ":/mnt/wordpress"