---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install htop
  apt:
    name: htop
    state: latest


#- name: Install common packages
#  apt:
#    name: "{{ item }}"
#    state: latest
#  with_items: "{{ common_packages }}"
