version: "3.3"

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: infoshare
      MYSQL_DATABASE: lms
      MYSQL_USER: lms
      MYSQL_PASSWORD: lms-pass
    ports:
      - "3306:3306"

  lms:
    depends_on:
      - db
    image: lms:dev
    ports:
      - "80:80"
    restart: always
    environment:
      SQL_TYPE: mysql
      MYSQL_HOST: db
      MYSQL_DATABASE: lms
      MYSQL_USER: lms
      MYSQL_PASS: lms-pass
    links:
      - db
