---
- hosts: all

  tasks:
    - ping:
    - name: Tworzy pliczek
      file:
        path: /home/vagrant/pliczek
        owner: vagrant
        state: touch
    - name: Stwórz poufne_dane_klienta
      ansible.builtin.file:
        path: /home/vagrant/poufne_dane_klienta
        owner: vagrant
        state: touch
    - name: Install vim
      package:
        state: present
        name: vim
      become: yes
