---
- hosts: app_servers
  become: true
  tasks:
    - name: Add several users
      user:
        name: "{{ item }}"
        state: present
      with_items:
        - alice
        - barbara

    - name: Add several users - some with home, some without
      user:
        name: "{{ item.name }}"
        state: present
        create_home: "{{ item.home }}"
      with_items:
        - {name: adam, home: no}
        - {name: bob, home: yes}
