---
- hosts: target1
  become: false

  tasks:
    - name: Register a variable, ignore errors and continue
      ansible.builtin.command: /bin/false
      register: result
      ignore_errors: true

    - name: Run only if the task that registered the "result" variable fails
      ansible.builtin.command: echo failed
      when: result is failed

    - name: Run only if the task that registered the "result" variable succeeds
      ansible.builtin.command: echo succeeded
      when: result is succeeded
      register: result2

    - name: Run only if the task that registered the "result2" variable is skipped
      ansible.builtin.command: echo skipped
      when: result2 is skipped