---
- name: Create directory
  file:
    state: directory
    path: "{{ data_path }}"
    owner: "{{ ansible_user }}"

- name: Create an empty file
  copy:
    src: files/tajne
    dest: "{{ data_path }}/tajne"
    owner: "{{ ansible_user }}"
    mode: 0600